#Project

In [1]:
!pip install transformers
import transformers

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting transformers
  Downloading transformers-4.30.1-py3-none-any.whl (7.2 MB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 7.2/7.2 MB 56.4 MB/s eta 0:00:00
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from transformers) (3.12.0)
Collecting huggingface-hub<1.0,>=0.14.1 (from transformers)
  Downloading huggingface_hub-0.15.1-py3-none-any.whl (236 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 236.8/236.8 kB 26.0 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from transformers) (23.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from transformers) (6.0)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.10/dist-packages (from transformers) (2022.10.31)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from transformers) (2.27.1)
Collecting tokenizers!=0.11.3,<0.14,>=0.11.1 (from transformers)
  Downloading tokenizers-0.13.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.8 MB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 7.8/7.8 MB 79.1 MB/s eta 0:00:00
Collecting safetensors>=0.3.1 (from transformers)
  Downloading safetensors-0.3.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 1.3/1.3 MB 69.6 MB/s eta 0:00:00
Requirement already satisfied: tqdm>=4.27 in /usr/local/lib/python3.10/dist-packages (from transformers) (4.65.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (2023.4.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub<1.0,>=0.14.1->transformers) (4.6.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->transformers) (3.4)
Installing collected packages: tokenizers, safetensors, huggingface-hub, transformers
Successfully installed huggingface-hub-0.15.1 safetensors-0.3.1 tokenizers-0.13.3 transformers-4.30.1

In [2]:
from transformers import AutoModelForSequenceClassification, AutoTokenizer, pipeline

model = AutoModelForSequenceClassification.from_pretrained("savasy/bert-base-turkish-sentiment-cased")
tokenizer = AutoTokenizer.from_pretrained("savasy/bert-base-turkish-sentiment-cased", from_tf=True)
sa= pipeline("sentiment-analysis", tokenizer=tokenizer, model=model, padding="max_length", truncation=True)

p = sa("bu telefon modelleri Ã§ok kaliteli , her parÃ§asÄ± Ã§ok Ã¶zel bence")
print(p)
# [{'label': 'positive', 'score': 0.9871089}]
print(p[0]['label'] == 'LABEL_1')
# True

p = sa("Film Ã§ok kÃ¶tÃ¼ ve Ã§ok sahteydi")
print(p)
# [{'label': 'negative', 'score': 0.9975505}]
print(p[0]['label'] == 'LABEL_1')
# False

Downloading (â€¦)lve/main/config.json:   0%|          | 0.00/596 [00:00<?, ?B/s]

Downloading pytorch_model.bin:   0%|          | 0.00/443M [00:00<?, ?B/s]

Downloading (â€¦)okenizer_config.json:   0%|          | 0.00/39.0 [00:00<?, ?B/s]

Downloading (â€¦)solve/main/vocab.txt:   0%|          | 0.00/263k [00:00<?, ?B/s]

Downloading (â€¦)cial_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

Xformers is not installed correctly. If you want to use memory_efficient_attention to accelerate training use the following command to install Xformers
pip install xformers.

[{'label': 'positive', 'score': 0.983146607875824}]
False
[{'label': 'negative', 'score': 0.9990053772926331}]
False

In [3]:
import pandas as pd
import numpy as np

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [5]:
data = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/encoded-hepsiburada-product-comments.csv', sep=",")

In [6]:
data.columns = ['Ã¼rÃ¼n', 'yorum', 'yÄ±ldÄ±z', '?', '??']

In [7]:
data

,Ã¼rÃ¼n,yorum,yÄ±ldÄ±z,?,??
0,Uno Flip,"Merhaba, \nDaha Ã¶nce yapmÄ±ÅŸ olduÄŸum yorumda ka...",5,3,1
1,Uno Flip,Gayet gÃ¼zel hÄ±zlÄ± geldi,5,4,4
2,Uno Flip,Klasik ve diÄŸer uno da gayet gÃ¼zeldi bu da Ã§ok...,5,8,2
3,Uno Flip,"Kart ile alakalÄ± bir iki defo sorunu vardÄ±, yo...",5,0,0
4,Uno Flip,Acayip eÄŸlenceli orjinal UNO nun bir tÃ¼rÃ¼ eÄŸle...,5,8,3
...,...,...,...,...,...
947025,KÄ±raÃ§ Dekoratif Duvar Dekorasyon TÃ¼y Desen Ayn...,"Ayna Ã¶zelliÄŸi tansiyon Ã§Ä±kartan cinsten ,",1,2,0
947026,KÄ±raÃ§ Dekoratif Duvar Dekorasyon TÃ¼y Desen Ayn...,Dekor olarak gÃ¼zel ama ayna olarak normal,4,0,0
947027,KÄ±raÃ§ Dekoratif Duvar Dekorasyon TÃ¼y Desen Ayn...,ÃœrÃ¼n anlatÄ±ldÄ±ÄŸÄ± gibi ilgili satici ve cok guz...,5,2,2
947028,KÄ±raÃ§ Dekoratif Duvar Dekorasyon TÃ¼y Desen Ayn...,ÃœrÃ¼n gÃ¼zel fakat yapÄ±ÅŸtÄ±rÄ±cÄ±larÄ± Ã§ok kalitesiz...,1,14,0
947029,KÄ±raÃ§ Dekoratif Duvar Dekorasyon TÃ¼y Desen Ayn...,25X100 olan Ã¼rÃ¼n fotoÄŸraflarda yok gerÃ§ekten k...,1,5,0

#Veriyi kÃ¼Ã§Ã¼ltme

In [8]:
yorum = data.yorum[0]
yorum

"Merhaba, \nDaha Ã¶nce yapmÄ±ÅŸ olduÄŸum yorumda kartlardan birkaÃ§ tanesinin hatalÄ± Ã§Ä±ktÄ±ÄŸÄ±nÄ± yazmÄ±ÅŸtÄ±m. ÃœrÃ¼nÃ¼n satÄ±cÄ±sÄ± (megahediyelik) benimle iletiÅŸime geÃ§erek yeni Ã¼rÃ¼n gÃ¶ndereceÄŸini belirtti. YanÄ±nda bir de hediye gÃ¶ndermiÅŸler, bu nazik davranÄ±ÅŸlarÄ± iÃ§in kendilerine teÅŸekkÃ¼r ediyorum. Kargo hÄ±zlÄ±ydÄ±, megahediyelik'ten ÅŸaÅŸmayÄ±n ğŸ‘ğŸ»"

In [9]:
p = sa(yorum)
p[0]['label']

'negative'

In [10]:
def sent_analyzer(yorum):
  p = sa(yorum)
  return p[0]['label']

In [11]:
sub_data = data[:10]

In [12]:
sub_data

,Ã¼rÃ¼n,yorum,yÄ±ldÄ±z,?,??
0,Uno Flip,"Merhaba, \nDaha Ã¶nce yapmÄ±ÅŸ olduÄŸum yorumda ka...",5,3,1
1,Uno Flip,Gayet gÃ¼zel hÄ±zlÄ± geldi,5,4,4
2,Uno Flip,Klasik ve diÄŸer uno da gayet gÃ¼zeldi bu da Ã§ok...,5,8,2
3,Uno Flip,"Kart ile alakalÄ± bir iki defo sorunu vardÄ±, yo...",5,0,0
4,Uno Flip,Acayip eÄŸlenceli orjinal UNO nun bir tÃ¼rÃ¼ eÄŸle...,5,8,3
5,ToptancÄ± KapÄ±nda 7 Renk DeÄŸiÅŸtiren AlarmlÄ± Dij...,Ã¼rÃ¼n aynen gÃ¶rÃ¼ndÃ¼ÄŸÃ¼ gibi gÃ¼zel Ã§ok kaliteli d...,4,2,0
6,Uno Flip,Klasik uno kartlarÄ±ndan biraz kÃ¼Ã§Ã¼k boyutta bu...,5,3,3
7,Uno Flip,"Ã‡ok zevkli bir oyun, tek eksiÄŸi iÃ§inde oynama ...",5,0,1
8,Uno Flip,Evdekiler ile veya arkadaÅŸlarÄ±niz ile guzel va...,4,0,1
9,Uno Flip,Kargom hÄ±zlÄ± geldi Ã¼stelik klasik uno ya gÃ¶re ...,5,1,1

In [13]:
sub_data['duygu'] = sub_data['yorum'].apply(sent_analyzer)

<ipython-input-13-bb883a424068>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  sub_data['duygu'] = sub_data['yorum'].apply(sent_analyzer)

In [14]:
sub_data

,Ã¼rÃ¼n,yorum,yÄ±ldÄ±z,?,??,duygu
0,Uno Flip,"Merhaba, \nDaha Ã¶nce yapmÄ±ÅŸ olduÄŸum yorumda ka...",5,3,1,negative
1,Uno Flip,Gayet gÃ¼zel hÄ±zlÄ± geldi,5,4,4,negative
2,Uno Flip,Klasik ve diÄŸer uno da gayet gÃ¼zeldi bu da Ã§ok...,5,8,2,positive
3,Uno Flip,"Kart ile alakalÄ± bir iki defo sorunu vardÄ±, yo...",5,0,0,positive
4,Uno Flip,Acayip eÄŸlenceli orjinal UNO nun bir tÃ¼rÃ¼ eÄŸle...,5,8,3,positive
5,ToptancÄ± KapÄ±nda 7 Renk DeÄŸiÅŸtiren AlarmlÄ± Dij...,Ã¼rÃ¼n aynen gÃ¶rÃ¼ndÃ¼ÄŸÃ¼ gibi gÃ¼zel Ã§ok kaliteli d...,4,2,0,negative
6,Uno Flip,Klasik uno kartlarÄ±ndan biraz kÃ¼Ã§Ã¼k boyutta bu...,5,3,3,negative
7,Uno Flip,"Ã‡ok zevkli bir oyun, tek eksiÄŸi iÃ§inde oynama ...",5,0,1,positive
8,Uno Flip,Evdekiler ile veya arkadaÅŸlarÄ±niz ile guzel va...,4,0,1,negative
9,Uno Flip,Kargom hÄ±zlÄ± geldi Ã¼stelik klasik uno ya gÃ¶re ...,5,1,1,positive

#Daha bÃ¼yÃ¼k bir subset

In [15]:
sub_data = data[:1000]

In [16]:
sub_data

,Ã¼rÃ¼n,yorum,yÄ±ldÄ±z,?,??
0,Uno Flip,"Merhaba, \nDaha Ã¶nce yapmÄ±ÅŸ olduÄŸum yorumda ka...",5,3,1
1,Uno Flip,Gayet gÃ¼zel hÄ±zlÄ± geldi,5,4,4
2,Uno Flip,Klasik ve diÄŸer uno da gayet gÃ¼zeldi bu da Ã§ok...,5,8,2
3,Uno Flip,"Kart ile alakalÄ± bir iki defo sorunu vardÄ±, yo...",5,0,0
4,Uno Flip,Acayip eÄŸlenceli orjinal UNO nun bir tÃ¼rÃ¼ eÄŸle...,5,8,3
...,...,...,...,...,...
995,Bio-oil Ã‡atlak KarÅŸÄ±tÄ± & Nemlendirici Cilt Bak...,"ÃœrÃ¼n dÃ¼n gece aldÄ±m, bugÃ¼n elime ulaÅŸtÄ±. Bu ne...",5,0,0
996,Bio-oil Ã‡atlak KarÅŸÄ±tÄ± & Nemlendirici Cilt Bak...,Hamilelik sÃ¼reci iÃ§in aldÄ±m ve ilk kez kullanm...,4,0,0
997,Bio-oil Ã‡atlak KarÅŸÄ±tÄ± & Nemlendirici Cilt Bak...,Ã¼rÃ¼n orjinal.\nDaha Ã¶ncede kullanÄ±p memnun kal...,5,0,0
998,OtacÄ± DoÄŸal GÃ¼l Suyu 150 ml,satici firmaya cok tesekkurler gayet muntazam ...,5,0,0
999,Bioderma Sebium Foaming Gel - Karma&YaÄŸlÄ± Cilt...,ÃœrÃ¼n paketlenmesi Ã§ok iyiydi maket bÄ±Ã§aÄŸÄ±yla z...,5,3,0

In [17]:
!pip install evaluate

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting evaluate
  Downloading evaluate-0.4.0-py3-none-any.whl (81 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 81.4/81.4 kB 3.6 MB/s eta 0:00:00
Collecting datasets>=2.0.0 (from evaluate)
  Downloading datasets-2.12.0-py3-none-any.whl (474 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 474.6/474.6 kB 16.7 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.24.3)
Collecting dill (from evaluate)
  Downloading dill-0.3.6-py3-none-any.whl (110 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 110.5/110.5 kB 14.0 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from evaluate) (1.5.3)
Requirement already satisfied: requests>=2.19.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2.27.1)
Requirement already satisfied: tqdm>=4.62.1 in /usr/local/lib/python3.10/dist-packages (from evaluate) (4.65.0)
Collecting xxhash (from evaluate)
  Downloading xxhash-3.2.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (212 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 212.5/212.5 kB 25.3 MB/s eta 0:00:00
Collecting multiprocess (from evaluate)
  Downloading multiprocess-0.70.14-py310-none-any.whl (134 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 134.3/134.3 kB 17.3 MB/s eta 0:00:00
Requirement already satisfied: fsspec[http]>=2021.05.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (2023.4.0)
Requirement already satisfied: huggingface-hub>=0.7.0 in /usr/local/lib/python3.10/dist-packages (from evaluate) (0.15.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.10/dist-packages (from evaluate) (23.1)
Collecting responses<0.19 (from evaluate)
  Downloading responses-0.18.0-py3-none-any.whl (38 kB)
Requirement already satisfied: pyarrow>=8.0.0 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (9.0.0)
Collecting aiohttp (from datasets>=2.0.0->evaluate)
  Downloading aiohttp-3.8.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 1.0/1.0 MB 48.7 MB/s eta 0:00:00
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.10/dist-packages (from datasets>=2.0.0->evaluate) (6.0)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (3.12.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /usr/local/lib/python3.10/dist-packages (from huggingface-hub>=0.7.0->evaluate) (4.6.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2022.12.7)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (2.0.12)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests>=2.19.0->evaluate) (3.4)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->evaluate) (2022.7.1)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.10/dist-packages (from aiohttp->datasets>=2.0.0->evaluate) (23.1.0)
Collecting multidict<7.0,>=4.5 (from aiohttp->datasets>=2.0.0->evaluate)
  Downloading multidict-6.0.4-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (114 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 114.5/114.5 kB 14.4 MB/s eta 0:00:00
Collecting async-timeout<5.0,>=4.0.0a3 (from aiohttp->datasets>=2.0.0->evaluate)
  Downloading async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting yarl<2.0,>=1.0 (from aiohttp->datasets>=2.0.0->evaluate)
  Downloading yarl-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (268 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 268.8/268.8 kB 31.8 MB/s eta 0:00:00
Collecting frozenlist>=1.1.1 (from aiohttp->datasets>=2.0.0->evaluate)
  Downloading frozenlist-1.3.3-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (149 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 149.6/149.6 kB 18.0 MB/s eta 0:00:00
Collecting aiosignal>=1.1.2 (from aiohttp->datasets>=2.0.0->evaluate)
  Downloading aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->evaluate) (1.16.0)
Installing collected packages: xxhash, multidict, frozenlist, dill, async-timeout, yarl, responses, multiprocess, aiosignal, aiohttp, datasets, evaluate
Successfully installed aiohttp-3.8.4 aiosignal-1.3.1 async-timeout-4.0.2 datasets-2.12.0 dill-0.3.6 evaluate-0.4.0 frozenlist-1.3.3 multidict-6.0.4 multiprocess-0.70.14 responses-0.18.0 xxhash-3.2.0 yarl-1.9.2

In [18]:
from sklearn.model_selection import train_test_split
validation_size = 0.2
train_df, test_df = train_test_split(sub_data, test_size=validation_size, random_state=42)

In [19]:
test_df.shape

(200, 5)

In [20]:
train_df.shape

(800, 5)

In [21]:
from datasets import Dataset
hg_test_data = Dataset.from_pandas(test_df)
hg_train_data = Dataset.from_pandas(train_df)

In [22]:
hg_train_data[0]

{'Ã¼rÃ¼n': 'Ks Games Metropol Emlak Ticareti Oyunu',
 'yorum': 'Oyun muadillerini aratmÄ±yor hatta fark yok diye biliriz. Paketleme gayet gÃ¼zel, oyun sahasÄ±, piyonlar kartlar gayet gÃ¼zel, bir tek oyun parasÄ± biraz daha kaliteli olsa iyi olurdu. Ã‡Ã¼nkÃ¼ en Ã§ok elde dolaÅŸan ve kullanÄ±lan o. Oyun talimatlarÄ± gayet aÃ§Ä±klayÄ±cÄ±. Muadiline o kadar paralar vermek saÃ§ma olur. Ki aslÄ±nda muadili ile kÄ±yaslamak belki de haksÄ±zlÄ±k olacak derecede tatmin edici bir Ã¼rÃ¼n.',
 'yÄ±ldÄ±z': 5,
 '?': 6,
 '??': 0,
 '__index_level_0__': 29}

In [23]:
def tokenize_dataset(data):
  return tokenizer(data["yorum"],
                   max_length = 32,
                   truncation = True,
                   padding = "max_length")
# Tokenize the dataset
dataset_train = hg_train_data.map(tokenize_dataset)
dataset_test = hg_test_data.map(tokenize_dataset)
dataset_train.with_format("tensorflow")
dataset_test.with_format("tensorflow")

Map:   0%|          | 0/800 [00:00<?, ? examples/s]

Map:   0%|          | 0/200 [00:00<?, ? examples/s]

Dataset({
    features: ['Ã¼rÃ¼n', 'yorum', 'yÄ±ldÄ±z', '?', '??', '__index_level_0__', 'input_ids', 'token_type_ids', 'attention_mask'],
    num_rows: 200
})

In [24]:
import evaluate

In [25]:
from transformers import TrainingArguments, Trainer, EarlyStoppingCallback, TextClassificationPipeline

In [26]:
def compute_metrics(eval_pred):
  metric = evaluate.load("accuracy")
  logits, labels = eval_pred
  predictions = np.argmax(logits, axis=1)
  return metric.compute(predictions=predictions, references=labels)

In [27]:
!pip install accelerate -U

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting accelerate
  Downloading accelerate-0.20.3-py3-none-any.whl (227 kB)
     â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â”â” 227.6/227.6 kB 5.8 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.17 in /usr/local/lib/python3.10/dist-packages (from accelerate) (1.24.3)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (23.1)
Requirement already satisfied: psutil in /usr/local/lib/python3.10/dist-packages (from accelerate) (5.9.5)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.10/dist-packages (from accelerate) (6.0)
Requirement already satisfied: torch>=1.6.0 in /usr/local/lib/python3.10/dist-packages (from accelerate) (2.0.1+cu118)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (3.12.0)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (4.6.3)
Requirement already satisfied: sympy in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (1.11.1)
Requirement already satisfied: networkx in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (3.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (3.1.2)
Requirement already satisfied: triton==2.0.0 in /usr/local/lib/python3.10/dist-packages (from torch>=1.6.0->accelerate) (2.0.0)
Requirement already satisfied: cmake in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->accelerate) (3.25.2)
Requirement already satisfied: lit in /usr/local/lib/python3.10/dist-packages (from triton==2.0.0->torch>=1.6.0->accelerate) (16.0.5)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2->torch>=1.6.0->accelerate) (2.1.2)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.10/dist-packages (from sympy->torch>=1.6.0->accelerate) (1.3.0)
Installing collected packages: accelerate
Successfully installed accelerate-0.20.3

In [29]:
from transformers import TrainingArguments
training_args = TrainingArguments(
    output_dir = "/content/our-model",
    learning_rate=2e-5,
    per_device_train_batch_size= 64,
    per_device_eval_batch_size = 16,
    num_train_epochs = 2,
    weight_decay = 0.01,
    evaluation_strategy = "epoch",
    save_strategy = "epoch",
    load_best_model_at_end = True,
    push_to_hub = False
)

ImportError: ignored

In [ ]:
from transformers import DataCollatorWithPadding
data_collator = DataCollatorWithPadding(tokenizer)

In [ ]:
from transformers import Trainer
trainer = Trainer(
    model=model,
    train_dataset=dataset_train,
    eval_dataset=dataset_test,
    compute_metrics=compute_metrics,
    data_collator = data_collator,
    callbacks=[EarlyStoppingCallback(early_stopping_patience=1)]
)
trainer.train()

In [ ]:
sub_data['duygu'] = sub_data['yorum'].apply(sent_analyzer)